apiVersion: v1
appVersion: 1.10.12
deprecated: true
description: 'DEPRECATED - please use: https://github.com/airflow-helm/charts/tree/main/charts/airflow'
home: https://airflow.apache.org/
icon: https://airflow.apache.org/_images/pin_large.png
keywords:
- workflow
- dag
- airflow
name: airflow
sources:
- https://airflow.apache.org/
version: 7.13.3
